
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "yaf/config/exception.zep.h"
#include "yaf/config/ini.zep.h"
#include "yaf/config/simple.zep.h"
#include "yaf/exception/loadfailed/action.zep.h"
#include "yaf/exception/loadfailed/controller.zep.h"
#include "yaf/exception/loadfailed/loadfailed.zep.h"
#include "yaf/exception/loadfailed/module.zep.h"
#include "yaf/exception/loadfailed/view.zep.h"
#include "yaf/exception/dispatchfailed.zep.h"
#include "yaf/exception/routerfailed.zep.h"
#include "yaf/exception/startuperror.zep.h"
#include "yaf/exception/typeerror.zep.h"
#include "yaf/request/exception.zep.h"
#include "yaf/request/http.zep.h"
#include "yaf/request/simple.zep.h"
#include "yaf/response/cli.zep.h"
#include "yaf/response/exception.zep.h"
#include "yaf/response/http.zep.h"
#include "yaf/route/exception.zep.h"
#include "yaf/route/map.zep.h"
#include "yaf/route/regex.zep.h"
#include "yaf/route/rewrite.zep.h"
#include "yaf/route/simple.zep.h"
#include "yaf/route/supervar.zep.h"
#include "yaf/view/simple.zep.h"
#include "yaf/action_abstract.zep.h"
#include "yaf/application.zep.h"
#include "yaf/bootstrap_abstract.zep.h"
#include "yaf/config_abstract.zep.h"
#include "yaf/controller_abstract.zep.h"
#include "yaf/dispatcher.zep.h"
#include "yaf/exception.zep.h"
#include "yaf/g.zep.h"
#include "yaf/loader.zep.h"
#include "yaf/plugin_abstract.zep.h"
#include "yaf/registry.zep.h"
#include "yaf/request_abstract.zep.h"
#include "yaf/response_abstract.zep.h"
#include "yaf/route_interface.zep.h"
#include "yaf/route_static.zep.h"
#include "yaf/router.zep.h"
#include "yaf/session.zep.h"
#include "yaf/view_interface.zep.h"

#endif